### ISSUE TITLE
cannot install BrowserViz for R 4.1.0

### ISSUE THREAD

**Issue by jipingw** [paul-shannon/BrowserViz#1]
> 
> BiocManager::install("BrowserViz")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://mirror.las.iastate.edu/CRAN

Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.0 (2021-05-18)
Installing package(s) 'BrowserViz'
Warning message:
In .inet_warning(msg) :
  package ‘BrowserViz’ is not available for Bioconductor version '3.14'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by paul-shannon** [comment]
@jipingw - can you give me a little more detail, please?
The Bioconductor 3.14 landing page shows successful build, check and bin for all systems but ubuntu linux.  Is linux your target system for running BrowserViz?   If macos or windows, the bioc 3.14 BrowserViz binaries look good (to me):

    http://bioconductor.org/checkResults/devel/bioc-LATEST/BrowserViz/

That failure is due to the absence of a virtual web browser on that build system.   Herve intends to fix that, I believe.

Meanwhile it should be easy to build from source - I'd be glad to help with that if you wish.

 - Paul

**Comment by jipingw** [comment]
Thanks for your quick reply. I use mac osx.

But I was able to download your package from github and installed from the source. It was successful. I don’t know why I couldn’t get through from Bioconductor.

**Comment by paul-shannon** [comment]
Thanks, I’ll check into that.  I’m grateful for the tip.

May I ask how are you using BrowserViz?

 - Paul

**Comment by jipingw** [comment]
I was install igvR, which requires BrowserViz. It cannot be automatically installed when I install igvR for some reason so I had to install it separately.

**Comment by paul-shannon** [comment]
I will look into that. 

If you have suggestions for igvR, please let me know.

 - Paul

**Comment by jipingw** [comment]
thanks for your help. We had a package riboDiPA and trying to visualize the results through web browser. thanks for your igvR as well. I think it's a convenient package to provide an interface to IGV.
